version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: bitburst
  callback:
    build:
      context: .
    restart: always
    ports:
    - 9090:9090
  onlineservice:
    build:
      context: ./service
    restart: always
