host: ":9090"
service:
  host: "http://onlineservice:9010/objects"
database:
  dbname: "bitburst"
  driver: "postgres"
  host: "postgres"
  password: "password"
  port: 5432
  user: "user"
  ssl_mode: "disable"